/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14.4/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.10.0"
}

rootProject.name = "java-opa-sdk"

include("opa-evaluator")
include("opa-jackson")
include("opa-services")
include("opa-builtins")
include("opa-builtins:opa-builtins-time")
include("opa-builtins:opa-builtins-token")
include("opa-builtins:opa-builtins-regex")
include("opa-builtins:opa-builtins-semver")
include("opa-builtins:opa-builtins-net")
include("opa-builtins:opa-builtins-crypto")
include("opa-builtins:opa-builtins-json")
include("opa-slf4j")
